#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Python App"""

import argparse
import logging

from pytch.gui import start_gui


# commandline argument parser
if __name__ == '__main__':
    parser = argparse.ArgumentParser('pytch')
    parser.add_argument(
        '--debug', required=False, default=False,
        action='store_true',
        help='Set logging level.')

    args = parser.parse_args()

    logger = logging.getLogger('pytch')
    if args.debug:
        logger.setLevel(logging.DEBUG)
    else:
        logger.setLevel(logging.INFO)

    logger.debug("starting app...")

    start_gui()
